# Generated by Django 4.2.7 on 2023-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_task',
            name='desription',
        ),
        migrations.AddField(
            model_name='todo_task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
